# Generated by Django 2.1.7 on 2020-04-08 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('numguests', models.IntegerField(default=1)),
                ('cancelled', models.BooleanField(default=False)),
                ('checkin', models.DateField(null=True)),
                ('checkout', models.DateField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='amentie',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='room',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='room',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='room',
            name='customer',
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='room',
            name='luxury',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.DeleteModel(
            name='Amentie',
        ),
        migrations.AddField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.Room'),
        ),
    ]
