# Generated by Django 3.0.5 on 2020-04-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200408_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_num',
        ),
    ]
